const galleryData = [
  {
    id: 1,
    title: "Mountain Sunset",
    description: "Beautiful sunset over mountain ranges",
    category: "nature",
    imageUrl: "images/img1.jpg",
    likes: 0,
    date: "2025-04-15",
  },
  {
    id: 2,
    title: "City Skyline",
    description: "Downtown skyline at night with lights",
    category: "city",
    imageUrl: "images/img2.jpg",
    likes: 0,
    date: "2025-04-10",
  },
  {
    id: 3,
    title: "Colorful Patterns",
    description: "Abstract patterns with vibrant colors",
    category: "abstract",
    imageUrl: "images/img3.jpg",
    likes: 0,
    date: "2025-04-05",
  },
  {
    id: 4,
    title: "Wild Tiger",
    description: "Majestic tiger in its natural habitat",
    category: "animals",
    imageUrl: "images/img4.jpg",
    likes: 0,
    date: "2025-03-28",
  },
  {
    id: 5,
    title: "Tropical Beach",
    description: "Crystal clear waters and white sand",
    category: "nature",
    imageUrl: "images/img5.jpg",
    likes: 0,
    date: "2025-03-22",
  },
  {
    id: 6,
    title: "Urban Architecture",
    description: "Modern architectural masterpiece",
    category: "city",
    imageUrl: "images/img6.jpg",
    likes: 0,
    date: "2025-03-18",
  },
];
